- added to remove the authblocker when the device is existing auth succeeded - made auto-starting the storage configurable for better HA handling - improved remount_fs for Ubuntu Lucid and Maverick - added cloud-deployment hook, making the Cloud Storage types completely plug-able - added support for shared SAN storage - added fencing function, improve HA handling - added constraint-checks for object removal - added cloud-hook, making the Virtualization types completely plug-able - added ha-hook to auto-create and fence VMs
git-svn-id: https://openqrm.svn.sourceforge.net/svnroot/openqrm/trunk@2038 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/src/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-vm b/src/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-vm
--- a/src/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-vm
+++ b/src/plugins/kvm-storage/etc/templates/openqrm-kvm-storage-vm
@@ -21,8 +21,13 @@ KVM=`which kvm`
 if [ "$KVM" == "" ]; then
     KVM=`which qemu-kvm`
     if [ "$KVM" == "" ]; then
-        echo "ERROR: kvm ist not installed on this system !" | logger
-        exit 1
+        # maybe it is centos and not in the path
+        if [ -x /usr/libexec/qemu-kvm ]; then
+            KVM=/usr/libexec/qemu-kvm
+        else
+            echo "ERROR: kvm ist not installed on this system !" | logger
+            exit 1
+        fi
     fi
 fi
 # which screen binary to use
