commit of openQRM 4.8, for a detailed changelog please check https://sourceforge.net/projects/openqrm/files/openQRM-4.8/
git-svn-id: https://openqrm.svn.sourceforge.net/svnroot/openqrm/trunk@2109 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/src/etc/init.d/openqrm-client b/src/etc/init.d/openqrm-client
--- a/src/etc/init.d/openqrm-client
+++ b/src/etc/init.d/openqrm-client
@@ -6,7 +6,7 @@
 
 # support for LSB init scripts
 ### BEGIN INIT INFO
-# Provides:
+# Provides: openqrm-client
 # Required-Start: $all
 # Required-Stop: $all
 # Default-Start:  2 3 4 5
@@ -52,9 +52,9 @@ MAX_START_RETRY=120
 
 # define wget to use with https
 if [ "$openqrm_web_protocol" == "https" ]; then
-    WGET="wget -q --no-check-certificate"
+	WGET="wget -q --no-check-certificate"
 else
-    WGET="wget -q"
+	WGET="wget -q"
 fi
 
 # gets/starts/stops enabled boot-services for the resources
@@ -62,7 +62,7 @@ function openqrm_boot_service() {
 	local BOOT_SERVICE=$1
 	local BOOT_SERVICE_CMD=$2
 	local CURRENT=`pwd`
-	
+
 	# get + install the package during start
 	if [ "$BOOT_SERVICE_CMD" == "start" ]; then
 		echo "Getting boot-service package $BOOT_SERVICE"
@@ -73,7 +73,7 @@ function openqrm_boot_service() {
 			return 1
 		fi
 		tar -xzf boot-service-$BOOT_SERVICE.tgz
-		rm -f boot-service-$BOOT_SERVICE.tgz	
+		rm -f boot-service-$BOOT_SERVICE.tgz
 	fi
 	# run the boot-service cmd
 	BOOT_SERVICE_INIT="$resource_basedir/openqrm/plugins/$BOOT_SERVICE/etc/init.d/$BOOT_SERVICE"
@@ -91,29 +91,29 @@ function openqrm_boot_service() {
 function openqrm_client_start() {
 	echo "Starting openQRM-client"
 	openqrm_client_stop 1>/dev/null 2>&1
-    START_RETRY=0
+	START_RETRY=0
 	# checks
 	umount /initrd/lib/modules 1>/dev/null 2>&1
 	umount /initrd/boot 1>/dev/null 2>&1
 	umount /initrd/ 1>/dev/null 2>&1
 	grep -q "/initrd" /proc/mounts && umount /initrd
-    chmod 666 /dev/null
-    if [ ! -e /dev/tty ]; then
-        cd /dev
-        mknod tty c 5 0
-        cd
-    fi
-    # if not in the initrd try to refresh the resource parameters
-    if [ ! -f /etc/initrd-devices.conf ]; then
-        /bin/cp -f /var/openqrm/openqrm-resource.conf /var/openqrm/openqrm-resource.conf.last
-        if ! $WGET -q -t 1 -T 4 -O /var/openqrm/openqrm-resource.conf "$openqrm_web_protocol://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$resource_mac"; then
-            # restore
-            /bin/cp -f /var/openqrm/openqrm-resource.conf.last /var/openqrm/openqrm-resource.conf
-            echo "NOTICE: Could not refresh resource-parameters. Using previous one."
-        else
-            . /var/openqrm/openqrm-resource.conf
-        fi
-    fi
+	chmod 666 /dev/null
+	if [ ! -e /dev/tty ]; then
+		cd /dev
+		mknod tty c 5 0
+		cd
+	fi
+	# if not in the initrd try to refresh the resource parameters
+	if [ ! -f /etc/initrd-devices.conf ]; then
+		/bin/cp -f /var/openqrm/openqrm-resource.conf /var/openqrm/openqrm-resource.conf.last
+		if ! $WGET -q -t 1 -T 4 -O /var/openqrm/openqrm-resource.conf "$openqrm_web_protocol://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$resource_mac"; then
+			# restore
+			/bin/cp -f /var/openqrm/openqrm-resource.conf.last /var/openqrm/openqrm-resource.conf
+			echo "NOTICE: Could not refresh resource-parameters. Using previous one."
+		else
+			. /var/openqrm/openqrm-resource.conf
+		fi
+	fi
 
 	case "$openqrm_execution_layer" in
 		dropbear)
@@ -122,18 +122,18 @@ function openqrm_client_start() {
 			mkdir -p $resource_basedir/openqrm/etc/dropbear/
 			$resource_basedir/openqrm/bin/dropbearkey -t rsa -f $resource_basedir/openqrm/etc/dropbear/dropbear_rsa_host_key
 			# get the public key of the openQRM server
-            while (true); do
-                if ! $WGET $openqrm_web_protocol://$resource_openqrmserver/openqrm/boot-service/openqrm-server-public-rsa-key; then
-                    if [ "$START_RETRY" == "$MAX_START_RETRY" ]; then
-                        echo "ERROR: Could not get the public key of the openQRM-server at $resource_openqrmserver ! Please check the certificates !"
-                        return 1
-                    fi
-                    START_RETRY=$(( START_RETRY + 1 ))
-                    sleep 1
-                else
-                    break
-                fi
-            done
+			while (true); do
+				if ! $WGET $openqrm_web_protocol://$resource_openqrmserver/openqrm/boot-service/openqrm-server-public-rsa-key; then
+					if [ "$START_RETRY" == "$MAX_START_RETRY" ]; then
+						echo "ERROR: Could not get the public key of the openQRM-server at $resource_openqrmserver ! Please check the certificates !"
+						return 1
+					fi
+					START_RETRY=$(( START_RETRY + 1 ))
+					sleep 1
+				else
+					break
+				fi
+			done
 			if [ ! -d /root/.ssh ]; then
 				mkdir -p /root/.ssh
 				chmod 700 /root/.ssh
@@ -156,7 +156,7 @@ function openqrm_client_start() {
 				FORCE_INSTALL=true openqrm_install_os_dependency dropbear
 				# on debian and ubuntu, lets make sure it is not started as a service due to our install
 				if test -e /etc/default/dropbear; then
-					if grep '^NO_START=0' /etc/default/dropbear 1>/dev/null|| ! grep 'NO_START' /etc/default/dropbear 1>/dev/null; then 
+					if grep '^NO_START=0' /etc/default/dropbear 1>/dev/null|| ! grep 'NO_START' /etc/default/dropbear 1>/dev/null; then
 						# looks like it has been set to start by default; let's revert that
 						/etc/init.d/dropbear stop
 						sed -i -e "s/^NO_START=0/NO_START=1/g" /etc/default/dropbear
@@ -185,18 +185,22 @@ function openqrm_client_start() {
 	esac
 
 	if [ ! -f /etc/initrd-devices.conf ]; then
-        # upate package manager, the boot-services may want to install additional os-deps
-        openqrm_update_package_manager
+		# upate package manager, the boot-services may want to install additional os-deps
+		openqrm_update_package_manager
 		# start boot-services from enabled plugins
 		for boot_service in $openqrm_boot_services; do
 			openqrm_boot_service $boot_service start
 		done
 	fi
 	# start openqrm-monitord
-    if [ ! -d /tmp ]; then mkdir -p /tmp; fi
-    nohup $resource_basedir/openqrm/sbin/openqrm-monitord 1>/tmp/openqrm-monitord.out 2>&1 &
-    rm -f /tmp/openqrm-monitord.out
+	if [ ! -d /tmp ]; then mkdir -p /tmp; fi
+	nohup $resource_basedir/openqrm/sbin/openqrm-monitord 1>/tmp/openqrm-monitord.out 2>&1 &
+	rm -f /tmp/openqrm-monitord.out
 	openqrm_post_event $resource_id "openqrm-client" 5 openqrm_client_start "Resource $resource_id fully started"
+	# allow to overwrite the resource-configuration e.g. for cluster-resources
+	if [ -f /var/openqrm/openqrm-resource.conf.static ]; then
+		cat /var/openqrm/openqrm-resource.conf.static >> /var/openqrm/openqrm-resource.conf
+	fi
 	touch ${LOCKFILE}
 }
 
diff --git a/src/etc/templates/openqrm-linuxrc b/src/etc/templates/openqrm-linuxrc
--- a/src/etc/templates/openqrm-linuxrc
+++ b/src/etc/templates/openqrm-linuxrc
@@ -40,8 +40,8 @@ function prepare_udev() {
 		cp -a /dev/* /mnt/dev/
 		mkdir -p /mnt/dev/.udevdb/
 	fi
-    # clean udev rulez
-    rm -f /mnt/etc/udev/rules.d/*
+	# clean udev rulez
+	rm -f /mnt/etc/udev/rules.d/*
 }
 
 
@@ -71,7 +71,7 @@ function prepare_var() {
 		VAR_USER=${VAR_ARRAY[1]}
 		VAR_GROUP=${VAR_ARRAY[2]}
 		mkdir -p /mnt/var/run/$VAR_DIR
-		chown $VAR_USER:$VAR_GROUP /mnt/var/run/$VAR_DIR 1>/dev/null 
+		chown $VAR_USER:$VAR_GROUP /mnt/var/run/$VAR_DIR 1>/dev/null
 	done
 	unset IFS
 	return 0
@@ -83,22 +83,22 @@ function import_kernel() {
 	mount -t tmpfs none /tmp_download
 	mount -t tmpfs none /lib/modules
 	cd /tmp_download
-    if ! wget -q -O modules-$kernel_name.tgz http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/boot/modules-$kernel_name.tgz; then
-        tftp $OPENQRM_SERVER_IP_ADDRESS -g -r boot/modules-$kernel_name.tgz -l modules-$kernel_name.tgz
-    fi
+	if ! wget -q -O modules-$kernel_name.tgz http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/boot/modules-$kernel_name.tgz; then
+		tftp $OPENQRM_SERVER_IP_ADDRESS -g -r boot/modules-$kernel_name.tgz -l modules-$kernel_name.tgz
+	fi
 	tar -C / -xzf /tmp_download/modules-$kernel_name.tgz
 	rm -f modules-$kernel_name.tgz
 	sync
 	mkdir -p /boot
 	mount -t tmpfs none /boot
 	cd /boot
-    if ! wget -q -O vmlinuz-$kernel_name http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/boot/vmlinuz-$kernel_name; then
-    	tftp $OPENQRM_SERVER_IP_ADDRESS -g -r boot/vmlinuz-$kernel_name -l vmlinuz-$kernel_name
-    fi
+	if ! wget -q -O vmlinuz-$kernel_name http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/boot/vmlinuz-$kernel_name; then
+		tftp $OPENQRM_SERVER_IP_ADDRESS -g -r boot/vmlinuz-$kernel_name -l vmlinuz-$kernel_name
+	fi
 	mv vmlinuz-$kernel_name vmlinuz-$kernel_version
-    if ! wget -q -O System.map-$kernel_name http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/boot/System.map-$kernel_name; then
-    	tftp $OPENQRM_SERVER_IP_ADDRESS -g -r boot/System.map-$kernel_name -l System.map-$kernel_name
-    fi
+	if ! wget -q -O System.map-$kernel_name http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/boot/System.map-$kernel_name; then
+		tftp $OPENQRM_SERVER_IP_ADDRESS -g -r boot/System.map-$kernel_name -l System.map-$kernel_name
+	fi
 	mv System.map-$kernel_name System.map-$kernel_version
 	cd /
 	mknod /dev/ptmx c 5 2
@@ -114,42 +114,42 @@ function import_kernel() {
 	modprobe ata_piix 2>/mplog1
 	modprobe sata_nv 2>/mplog1
 	modprobe sd_mod 2>/mplog1
-    rm -f /mplog1
-    echo "- (2) Starting hardware detection (all system components)"
-    for module in `/sbin/pcimodules`; do
-        if [ "$module" == "matroxfb_base" ]; then
-            # skip this, it makes the kvm vm vnc console unreadable
-            continue
-        fi
-        if [ "$module" == "cirrusfb" ]; then
-            # skip this, it crashes the xen vm qemu-dm when accessing the vnc console on debian-lenny
-            continue
-        fi
-        echo " -- loading $module"
-        modprobe -s -k "$module"
-    done
+	rm -f /mplog1
+	echo "- (2) Starting hardware detection (all system components)"
+	for module in `/sbin/pcimodules`; do
+		if [ "$module" == "matroxfb_base" ]; then
+			# skip this, it makes the kvm vm vnc console unreadable
+			continue
+		fi
+		if [ "$module" == "cirrusfb" ]; then
+			# skip this, it crashes the xen vm qemu-dm when accessing the vnc console on debian-lenny
+			continue
+		fi
+		echo " -- loading $module"
+		modprobe -s -k "$module"
+	done
 	umount /tmp_download
 	rmdir /tmp_download
 	# start udev
 	udevd --daemon
 	# give time to settle, especially needed for some scsi devices
 	sleep 3
-    #lvm
-    if [ -x /bin/lvm ]; then
-        echo "- Scanning for physical lvm drives"
-        /bin/lvm pvscan
-        echo "- Scanning for logical volume groups"
-        /bin/lvm vgscan
-        echo "- Activating logical volume groups"
-        /bin/lvm vgchange -ay
-        echo "- Scanning for logical volumes"
-        /bin/lvm lvscan
-        echo "- Activating logical volumes"
-        for LVOL in `/bin/lvm lvdisplay | grep -i "LV Name" | awk {' print $3 '}`; do
-            echo "- Activating $LVOL"
-            /bin/lvm lvchange -ay $LVOL
-        done
-    fi
+	#lvm
+	if [ -x /bin/lvm ]; then
+		echo "- Scanning for physical lvm drives"
+		/bin/lvm pvscan
+		echo "- Scanning for logical volume groups"
+		/bin/lvm vgscan
+		echo "- Activating logical volume groups"
+		/bin/lvm vgchange -ay
+		echo "- Scanning for logical volumes"
+		/bin/lvm lvscan
+		echo "- Activating logical volumes"
+		for LVOL in `/bin/lvm lvdisplay | grep -i "LV Name" | awk {' print $3 '}`; do
+			echo "- Activating $LVOL"
+			/bin/lvm lvchange -ay $LVOL
+		done
+	fi
 }
 
 
@@ -161,22 +161,24 @@ function create_fstab_commons() {
 	echo "none	 /dev/shm     tmpfs    defaults	   0 0" >> $IMAGE_FSTAB
 	echo "/dev/fd0     /mnt/floppy  auto     noauto,owner,kudzu 0 0" >> $IMAGE_FSTAB
 	IFS=$'\n'
-	for IDEDEVICES in $(ls /proc/ide); do
-		if grep cdrom /proc/ide/$IDEDEVICES/media 1>/dev/null 2>&1; then
-			echo "Found cdrom at $IDEDEVICES"
-			mkdir -p /mnt/cdrom$LOOP 1>/dev/null 
-			echo "/dev/$IDEDEVICES     /mnt/cdrom$LOOP   udf,iso9660 noauto,owner,kudzu,ro 0 0" >> $IMAGE_FSTAB
-			LOOP=$(( LOOP +1 ))
-		fi
-	done
+	if [ -d /proc/ide ]; then
+		for IDEDEVICES in $(ls /proc/ide); do
+			if grep cdrom /proc/ide/$IDEDEVICES/media 1>/dev/null 2>&1; then
+				echo "Found cdrom at $IDEDEVICES"
+				mkdir -p /mnt/cdrom$LOOP 1>/dev/null
+				echo "/dev/$IDEDEVICES     /mnt/cdrom$LOOP   udf,iso9660 noauto,owner,kudzu,ro 0 0" >> $IMAGE_FSTAB
+				LOOP=$(( LOOP +1 ))
+			fi
+		done
+	fi
 	FOUND_SWAP=0
 	for SWPSPACE in $(cat /proc/partitions |grep '[0-9]' | awk '{print $4}'); do
-        if swapon /dev/${SWPSPACE} 1>/dev/null 2>&1; then
-            swapoff /dev/${SWPSPACE} 1>/dev/null
-            echo "Adding /dev/${SWPSPACE} as swap space"
-            echo "/dev/${SWPSPACE} swap	swap	defaults	0 0" >> $IMAGE_FSTAB
-            FOUND_SWAP=1
-        fi
+		if swapon /dev/${SWPSPACE} 1>/dev/null 2>&1; then
+			swapoff /dev/${SWPSPACE} 1>/dev/null
+			echo "Adding /dev/${SWPSPACE} as swap space"
+			echo "/dev/${SWPSPACE} swap	swap	defaults	0 0" >> $IMAGE_FSTAB
+			FOUND_SWAP=1
+		fi
 	done
 	if [ "$FOUND_SWAP" == "0" ]; then
 		# we need to create a small swap file
@@ -262,8 +264,8 @@ modprobe virtio_net 2>/mplog
 rm -f  /mplog
 echo "- (1) Starting hardware detection (network)"
 for module in `/sbin/pcimodules`; do
-    echo " -- loading $module"
-    modprobe -s -k "$module"
+	echo " -- loading $module"
+	modprobe -s -k "$module"
 done
 eval `cat /proc/cmdline`
 if grep -q sysfs /proc/filesystems ; then
@@ -272,7 +274,7 @@ fi
 
 # collecting some infos from /proc/cmdline
 OPENQRM_RESOURCE_MAC_ADDRESS=`echo $BOOTIF | sed -e "s/-/:/g"  | sed -e "s/^01://g" | tr '[:lower:]' '[:upper:]'`
-OPENQRM_RESOURCE_MANAGED_INTERFACE=`ifconfig -a | grep $OPENQRM_RESOURCE_MAC_ADDRESS | awk {' print $1 '}`
+OPENQRM_RESOURCE_MANAGED_INTERFACE=`ifconfig -a | grep $OPENQRM_RESOURCE_MAC_ADDRESS | awk {' print $1 '} | head -n 1`
 OPENQRM_RESOURCE_IP_ADDRESS=`echo $ip | cut -d':' -f1`
 OPENQRM_SERVER_IP_ADDRESS=`echo $ip | cut -d':' -f2`
 OPENQRM_RESOURCE_DEFAULT_GATEWAY=`echo $ip | cut -d':' -f3`
@@ -321,10 +323,10 @@ while (true); do
 	# try https first
 	if wget --no-check-certificate --random-file=/dev/random -q -O $OPENQRM_RESOURCE_PARAMETER_FILE "https://$OPENQRM_SERVER_IP_ADDRESS/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$id&resource_mac=$OPENQRM_RESOURCE_MAC_ADDRESS&resource_ip=$OPENQRM_RESOURCE_IP_ADDRESS"; then
 		if ! grep "<html>" $OPENQRM_RESOURCE_PARAMETER_FILE >/out; then
-        	echo "-> got parameters via https"
+			echo "-> got parameters via https"
 			break
 		fi
-        rm -f /out
+		rm -f /out
 	fi
 	# try http
 	if wget -q -O $OPENQRM_RESOURCE_PARAMETER_FILE "http://$OPENQRM_SERVER_IP_ADDRESS/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$id&resource_mac=$OPENQRM_RESOURCE_MAC_ADDRESS&resource_ip=$OPENQRM_RESOURCE_IP_ADDRESS"; then
@@ -332,9 +334,9 @@ while (true); do
 			echo "-> got parameter via http"
 			break
 		fi
-        rm -f /out
+		rm -f /out
 	fi
-    # no chance ?
+	# no chance ?
 	if [ "$NETWORKCARD_LOOP" == "10" ]; then
 		echo "ERROR: Could not reach the openQRM-Server at $OPENQRM_SERVER_IP_ADDRESS!"
 		# give a shell for the admin
@@ -348,9 +350,9 @@ done
 
 # define wget
 if [ "$openqrm_web_protocol" == "https" ]; then
-    export WGET="wget --no-check-certificate --random-file=/dev/random"
+	export WGET="wget --no-check-certificate --random-file=/dev/random"
 else
-    export WGET="wget"
+	export WGET="wget"
 fi
 
 # get kernel + modules by tftp
@@ -360,17 +362,17 @@ import_kernel
 # run default openqrm-client boot-service
 KERNEL_ARCH=`uname -m`
 if echo $KERNEL_ARCH | grep i.*86 1>/dev/null; then
-    # i386
-    OPENQRM_CLIENT_ARCH=i386
+	# i386
+	OPENQRM_CLIENT_ARCH=i386
 else
-    OPENQRM_CLIENT_ARCH=$KERNEL_ARCH
+	OPENQRM_CLIENT_ARCH=$KERNEL_ARCH
 fi
 
 cd /
 if ! $WGET -q -O openqrm-client.tgz "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.$OPENQRM_CLIENT_ARCH.tgz"; then
-    rm -f openqrm-client.tgz
-    echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one ..."
-    $WGET -q -O openqrm-client.tgz "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.tgz"
+	rm -f openqrm-client.tgz
+	echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one ..."
+	$WGET -q -O openqrm-client.tgz "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.tgz"
 fi
 tar -xzf openqrm-client.tgz
 rm -f openqrm-client.tgz
@@ -387,33 +389,33 @@ if [ "$image_type" == "ram" ] || [ "$image_type" == "" ]; then
 	if [ -x /init ]; then
 		echo "Detected initrd as initramfs, starting a shell"
 		/bin/bash
-	fi	
+	fi
 
 else
 	# if any deployment plugin is enabled, handle over the control
 	# -> deployment plugins will take care to mount the root fs
 	#    and do the pivot_root if needed
 
-    # pre-root-mount-hook to setup everything which needs to be done before the root-mount
+	# pre-root-mount-hook to setup everything which needs to be done before the root-mount
 	cd /
-    for boot_service in $openqrm_boot_services; do
-        if $WGET -q -O /pre-root-mount-hook.$boot_service "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/pre-root-mount-hook.$boot_service"; then
-            echo " - Running for pre-root-mount-hook of boot-service $boot_service"
-            chmod +x pre-root-mount-hook.$boot_service
-        	. ./pre-root-mount-hook.$boot_service
-            pre_mount_rootfs
-        else
-            rm -f /pre-root-mount-hook.$boot_service
-        fi
-    done
+	for boot_service in $openqrm_boot_services; do
+		if $WGET -q -O /pre-root-mount-hook.$boot_service "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/pre-root-mount-hook.$boot_service"; then
+			echo " - Running for pre-root-mount-hook of boot-service $boot_service"
+			chmod +x pre-root-mount-hook.$boot_service
+			. ./pre-root-mount-hook.$boot_service
+			pre_mount_rootfs
+		else
+			rm -f /pre-root-mount-hook.$boot_service
+		fi
+	done
 
-    # root-mount-hook
+	# root-mount-hook
 	eval $image_deployment_parameter
 	cd /
 	$WGET -q "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/root-mount.$image_type"
 	chmod +x root-mount.$image_type
-	# source the deployment plugin command, it will provide 
-	# the functions to mount/remount the rootfs at /mnt according 
+	# source the deployment plugin command, it will provide
+	# the functions to mount/remount the rootfs at /mnt according
 	# to the deployment-type and the image_deployment_parameters
 	. ./root-mount.$image_type
 
@@ -423,42 +425,42 @@ else
 	###############################################################
 	mount_rootfs
 
-    # here we have the rootfs mounted rw so we get the openQRM client according
-    # distro and arch
-    # find out the short distri name
-    if [ -f /mnt/etc/debian_version ]; then
-        # debian or ubuntu, try to find out without lsb-release which may not be installed
-        if grep -i ubuntu /mnt/etc/apt/sources.list 1>/dev/null; then
-            OPENQRM_SHORT_DISTRI_NAME="ubuntu"
-        else
-            OPENQRM_SHORT_DISTRI_NAME="debian"
-        fi
-    elif [ -f /mnt/etc/redhat-release ]; then
-        OPENQRM_SHORT_DISTRI_NAME="centos"
-    elif [ -f /mnt/etc/SuSE-release ]; then
-        OPENQRM_SHORT_DISTRI_NAME="suse"
-    else
-        OPENQRM_SHORT_DISTRI_NAME="custom"
-    fi
-    # get the openQRM client package fitting to distri + arch
-    rm -rf /mnt/$resource_basedir/openqrm
-    cd /
-    if [ "$OPENQRM_SHORT_DISTRI_NAME" != "" ]; then
-        echo "Getting openqrm-client package $OPENQRM_SHORT_DISTRI_NAME/$OPENQRM_CLIENT_ARCH"
-        if ! $WGET -q -O /mnt/openqrm-client.tgz "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.$OPENQRM_SHORT_DISTRI_NAME.$OPENQRM_CLIENT_ARCH.tgz"; then
-            rm -f /mnt/openqrm-client.tgz
-            echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one fitting $OPENQRM_CLIENT_ARCH"
-            # copy openQRM client which is on the initrd
-            mkdir /mnt/$resource_basedir/openqrm/
-            cp -a /$resource_basedir/openqrm/* /mnt/$resource_basedir/openqrm/
-        else
-            # use the openQRM client which fits to the distri and arch
-            cd /mnt/
-            tar -xzf openqrm-client.tgz
-            rm -f openqrm-client.tgz
-            cd /
-        fi
-    fi
+	# here we have the rootfs mounted rw so we get the openQRM client according
+	# distro and arch
+	# find out the short distri name
+	if [ -f /mnt/etc/debian_version ]; then
+		# debian or ubuntu, try to find out without lsb-release which may not be installed
+		if grep -i ubuntu /mnt/etc/apt/sources.list 1>/dev/null; then
+			OPENQRM_SHORT_DISTRI_NAME="ubuntu"
+		else
+			OPENQRM_SHORT_DISTRI_NAME="debian"
+		fi
+	elif [ -f /mnt/etc/redhat-release ]; then
+		OPENQRM_SHORT_DISTRI_NAME="centos"
+	elif [ -f /mnt/etc/SuSE-release ]; then
+		OPENQRM_SHORT_DISTRI_NAME="suse"
+	else
+		OPENQRM_SHORT_DISTRI_NAME="custom"
+	fi
+	# get the openQRM client package fitting to distri + arch
+	rm -rf /mnt/$resource_basedir/openqrm
+	cd /
+	if [ "$OPENQRM_SHORT_DISTRI_NAME" != "" ]; then
+		echo "Getting openqrm-client package $OPENQRM_SHORT_DISTRI_NAME/$OPENQRM_CLIENT_ARCH"
+		if ! $WGET -q -O /mnt/openqrm-client.tgz "$openqrm_web_protocol://$OPENQRM_SERVER_IP_ADDRESS/openqrm/boot-service/openqrm-client.$OPENQRM_SHORT_DISTRI_NAME.$OPENQRM_CLIENT_ARCH.tgz"; then
+			rm -f /mnt/openqrm-client.tgz
+			echo "WARNING: Failed to get the openqrm-client package arch $OPENQRM_CLIENT_ARCH ! Using default one fitting $OPENQRM_CLIENT_ARCH"
+			# copy openQRM client which is on the initrd
+			mkdir /mnt/$resource_basedir/openqrm/
+			cp -a /$resource_basedir/openqrm/* /mnt/$resource_basedir/openqrm/
+		else
+			# use the openQRM client which fits to the distri and arch
+			cd /mnt/
+			tar -xzf openqrm-client.tgz
+			rm -f openqrm-client.tgz
+			cd /
+		fi
+	fi
 
 	# fill /boot and /lib/modules on the fs-image
 	echo "Filling /boot and /lib/modules"
@@ -479,10 +481,6 @@ else
 
 	# transfer resource basedir
 	echo "Preparing resource openQRM client"
-
-
-
-
 
 	# copy resource parameter
 	mkdir -p /mnt/`dirname $OPENQRM_RESOURCE_PARAMETER_FILE`
@@ -510,7 +508,7 @@ else
 
 	# chroot + init
 	killall syslogd klogd 1>/dev/null 2>&1
-	killall udevd 
+	killall udevd 1>/dev/null 2>&1
 	sleep 2
 	if grep sysfs /proc/filesystems 1>/dev/null ; then
 		umount /sys
@@ -519,16 +517,8 @@ else
 	umount /boot
 	umount /lib/modules
 
-	cd /mnt
-
-	pivot_root . /mnt/initrd
-	export CONSOLE=/dev/console
-	if [ -e /usr/sbin/chroot ]; then
-		exec /usr/sbin/chroot . /sbin/init 3
-	else
-		exec /usr/bin/chroot . /sbin/init 3
-	fi
-	# here the system will do a normal init 
-	# from the mounted rootfs image	
+	exec switch_root /mnt /sbin/init
+	# here the system will do a normal init
+	# from the mounted rootfs image
 fi
 
