- remove the tftpboot link on uninstall - refresh resource-parameters during openqrm-client restart - enhanced openqrm-client start phase for HA - avoid starting bootservices on idle resource for faster startup
git-svn-id: https://openqrm.svn.sourceforge.net/svnroot/openqrm/trunk@2006 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/src/etc/init.d/openqrm-client b/src/etc/init.d/openqrm-client
--- a/src/etc/init.d/openqrm-client
+++ b/src/etc/init.d/openqrm-client
@@ -47,6 +47,9 @@ export OPENQRM_SOURCE_DIR=$resource_basedir/openqrm
 . $resource_basedir/openqrm/include/openqrm-functions
 . $resource_basedir/openqrm/include/openqrm-package-functions
 
+# define max-start-retries
+MAX_START_RETRY=120
+
 # define wget to use with https
 if [ "$openqrm_web_protocol" == "https" ]; then
     WGET="wget -q --no-check-certificate"
@@ -87,8 +90,8 @@ function openqrm_boot_service() {
 
 function openqrm_client_start() {
 	echo "Starting openQRM-client"
-
 	openqrm_client_stop 1>/dev/null 2>&1
+    START_RETRY=0
 	# checks
 	umount /initrd/lib/modules 1>/dev/null 2>&1
 	umount /initrd/boot 1>/dev/null 2>&1
@@ -100,6 +103,17 @@ function openqrm_client_start() {
         mknod tty c 5 0
         cd
     fi
+    # if not in the initrd try to refresh the resource parameters
+    if [ ! -f /etc/initrd-devices.conf ]; then
+        /bin/cp -f /var/openqrm/openqrm-resource.conf /var/openqrm/openqrm-resource.conf.last
+        if ! $WGET -q -t 1 -T 4 -O /var/openqrm/openqrm-resource.conf "$openqrm_web_protocol://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$resource_mac"; then
+            # restore
+            /bin/cp -f /var/openqrm/openqrm-resource.conf.last /var/openqrm/openqrm-resource.conf
+            echo "NOTICE: Could not refresh resource-parameters. Using previous one."
+        else
+            . /var/openqrm/openqrm-resource.conf
+        fi
+    fi
 
 	case "$openqrm_execution_layer" in
 		dropbear)
@@ -108,10 +122,18 @@ function openqrm_client_start() {
 			mkdir -p $resource_basedir/openqrm/etc/dropbear/
 			$resource_basedir/openqrm/bin/dropbearkey -t rsa -f $resource_basedir/openqrm/etc/dropbear/dropbear_rsa_host_key
 			# get the public key of the openQRM server
-			if ! $WGET $openqrm_web_protocol://$resource_openqrmserver/openqrm/boot-service/openqrm-server-public-rsa-key; then
-				echo "ERROR: Could not get the public key of the openQRM-server at $resource_openqrmserver ! Please check the certificates !"
-				return 1
-			fi
+            while (true); do
+                if ! $WGET $openqrm_web_protocol://$resource_openqrmserver/openqrm/boot-service/openqrm-server-public-rsa-key; then
+                    if [ "$START_RETRY" == "$MAX_START_RETRY" ]; then
+                        echo "ERROR: Could not get the public key of the openQRM-server at $resource_openqrmserver ! Please check the certificates !"
+                        return 1
+                    fi
+                    START_RETRY=$(( START_RETRY + 1 ))
+                    sleep 1
+                else
+                    break
+                fi
+            done
 			if [ ! -d /root/.ssh ]; then
 				mkdir -p /root/.ssh
 				chmod 700 /root/.ssh
@@ -162,7 +184,9 @@ function openqrm_client_start() {
 			;;
 	esac
 
-	if [ ! -f /linuxrc ]; then
+	if [ ! -f /etc/initrd-devices.conf ]; then
+        # upate package manager, the boot-services may want to install additional os-deps
+        openqrm_update_package_manager
 		# start boot-services from enabled plugins
 		for boot_service in $openqrm_boot_services; do
 			openqrm_boot_service $boot_service start
