commit of openQRM 4.8, for a detailed changelog please check https://sourceforge.net/projects/openqrm/files/openQRM-4.8/
git-svn-id: https://openqrm.svn.sourceforge.net/svnroot/openqrm/trunk@2145 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/src/plugins/vmware-esx/bin/openqrm-vmware-esx-init b/src/plugins/vmware-esx/bin/openqrm-vmware-esx-init
--- a/src/plugins/vmware-esx/bin/openqrm-vmware-esx-init
+++ b/src/plugins/vmware-esx/bin/openqrm-vmware-esx-init
@@ -28,8 +28,8 @@ export LANG=C
 
 # main
 if [ "$OPENQRM_SERVER_IP" == "" ] || [ "$ESX_SERVER_IP" == "" ] || [ "$USER" == "" ] || [ "$PASSWORD" == "" ]; then
-    echo "Usage : $0 <openqrm-server-ip> <esx-ip> <openqrm-user> <openqrm-password>"
-    exit 1
+	echo "Usage : $0 <openqrm-server-ip> <esx-ip> <openqrm-user> <openqrm-password>"
+	exit 1
 fi
 
 
@@ -42,20 +42,20 @@ if [ ! -f "$OPENQRM_RESOURCE_PARAMETER_FILE" ]; then
 	# remove whitespaces
 	resource_mac=`echo $resource_mac`
 	echo "Using $resource_ip/$resource_mac"
-    # https will fail since busybox on the esx does not support https connections
-    # try http
-    busybox wget -q -O $OPENQRM_RESOURCE_PARAMETER_FILE "http://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
-    sleep 2
-    # check if http was successfull
-    if ! grep resource_openqrmserver $OPENQRM_RESOURCE_PARAMETER_FILE 1>/dev/null 2>&1; then
-        echo "ERROR: Could not integrate the VMware ESX server into the openQRM-server at $OPENQRM_SERVER_IP!"
-        rm -f $MONITORD_LOCKFILE
-        exit 1
-    fi
+	# https will fail since busybox on the esx does not support https connections
+	# try http
+	busybox wget -q -O $OPENQRM_RESOURCE_PARAMETER_FILE "http://$OPENQRM_SERVER_IP/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_id=$resource_id&resource_mac=$resource_mac&resource_ip=$resource_ip"
+	sleep 2
+	# check if http was successfull
+	if ! grep resource_openqrmserver $OPENQRM_RESOURCE_PARAMETER_FILE 1>/dev/null 2>&1; then
+		echo "ERROR: Could not integrate the VMware ESX server into the openQRM-server at $OPENQRM_SERVER_IP!"
+		rm -f $MONITORD_LOCKFILE
+		exit 1
+	fi
 	. $OPENQRM_RESOURCE_PARAMETER_FILE
-    # https will fail since busybox on the esx does not support https connections
-    WGET_NO_CERT_CHECK=""
-    openqrm_web_protocol="http"
+	# https will fail since busybox on the esx does not support https connections
+	WGET_NO_CERT_CHECK=""
+	openqrm_web_protocol="http"
 
 	# gather some more details to create the appliance on the openQRM-server
 	local_server_root_device=`mount | grep ' / ' | awk {' print $1 '}`
@@ -75,30 +75,30 @@ if [ ! -f "$OPENQRM_RESOURCE_PARAMETER_FILE" ]; then
 		exit 1
 	fi
 
-    # start montitord
-    if `which screen 2>/dev/null`; then
-        if [ -x /usr/bin/screen.real ]; then
-            RUNSCREEN="/usr/bin/screen.real"
-        else
-            RUNSCREEN=`which screen`
-        fi
+	# start montitord
+	if `which screen 2>/dev/null`; then
+		if [ -x /usr/bin/screen.real ]; then
+			RUNSCREEN="/usr/bin/screen.real"
+		else
+			RUNSCREEN=`which screen`
+		fi
 		SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
-        OPENQRM_ESX_MONITORD_START_CMD="$RUNSCREEN -dmS openqrm-montitord /bin/openqrm-vmware-esx-monitord"
-    else
-        OPENQRM_ESX_MONITORD_START_CMD="busybox nohup /bin/openqrm-vmware-esx-monitord &"
-    fi
-    # add to init
-    # check which esx version we are running
-    if [ -f /etc/redhat-release ]; then
-        chkconfig --add openqrm-esx-monitord
-    fi
-    $OPENQRM_ESX_MONITORD_START_CMD
+		OPENQRM_ESX_MONITORD_START_CMD="$RUNSCREEN -dmS openqrm-montitord /bin/openqrm-vmware-esx-monitord"
+	else
+		OPENQRM_ESX_MONITORD_START_CMD="busybox nohup /bin/openqrm-vmware-esx-monitord &"
+	fi
+	# add to init
+	# check which esx version we are running
+	if [ -f /etc/redhat-release ]; then
+		chkconfig --add openqrm-esx-monitord
+	fi
+	$OPENQRM_ESX_MONITORD_START_CMD
 
 else
-    echo "ERROR: This ESX Server is already integrated in openQRM!"
-    echo "To re-integrate it please remove : $OPENQRM_RESOURCE_PARAMETER_FILE"
-    echo "and try again"
-    exit 1
+	echo "ERROR: This ESX Server is already integrated in openQRM!"
+	echo "To re-integrate it please remove : $OPENQRM_RESOURCE_PARAMETER_FILE"
+	echo "and try again"
+	exit 1
 fi
 
 
diff --git a/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord b/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
--- a/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
+++ b/src/plugins/vmware-esx/bin/openqrm-vmware-esx-monitord
@@ -24,9 +24,9 @@ OPENQRM_RESOURCE_PARAMETER_FILE="/var/openqrm/openqrm-resource.conf"
 export LANG=C
 
 if [ ! -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
-    echo "ERROR: Not initialyzed yet ! Please run :"
-    echo "  /bin/openqrm-start-vmware-esx-init <openqrm-server-ip-address> <esx-server-ip-address> <openqrm-user> <openqrm-password>"
-    exit 1
+	echo "ERROR: Not initialyzed yet ! Please run :"
+	echo "  /bin/openqrm-start-vmware-esx-init <openqrm-server-ip-address> <esx-server-ip-address> <openqrm-user> <openqrm-password>"
+	exit 1
 fi
 . $OPENQRM_RESOURCE_PARAMETER_FILE
 
@@ -36,14 +36,14 @@ if [ "$MONITOR_CMD" == "stop" ]; then
 		kill `cat $MONITORD_LOCKFILE`
 		rm -f $MONITORD_LOCKFILE
 	fi
-    kill `ps -c | grep openqrm | grep vmware-esx | grep -v grep | awk {' print $1 '}` 2>/dev/null
+	kill `ps -c | grep openqrm | grep vmware-esx | grep -v grep | awk {' print $1 '}` 2>/dev/null
 fi
 
 # create lockfile
 if [ -f "$MONITORD_LOCKFILE" ]; then
-    kill `cat $MONITORD_LOCKFILE` 2>/dev/null
-    rm -f $MONITORD_LOCKFILE
-    kill `ps -c | grep openqrm | grep vmware-esx | grep -v grep | awk {' print $1 '}` 2>/dev/null
+	kill `cat $MONITORD_LOCKFILE` 2>/dev/null
+	rm -f $MONITORD_LOCKFILE
+	kill `ps -c | grep openqrm | grep vmware-esx | grep -v grep | awk {' print $1 '}` 2>/dev/null
 fi
 echo "starting $0"
 echo $$ > $MONITORD_LOCKFILE
@@ -56,19 +56,19 @@ openqrm_web_protocol="http"
 # try to register all vms
 ESX_VER=$(vmware -v | awk '{print $4}')
 if [ -f /bin/vim-cmd ]; then
-    VMWARE_CMD=/bin/vim-cmd
+	VMWARE_CMD=/bin/vim-cmd
 elif [ -f /usr/bin/vmware-vim-cmd ]; then
-    VMWARE_CMD=/usr/bin/vmware-vim-cmd
+	VMWARE_CMD=/usr/bin/vmware-vim-cmd
 elif [[ "${ESX_VER}" == "3.0.3" ]] || [[ "${ESX_VER}" == "3.0.2" ]] || [[ "${ESX_VER}" == "3.0.1" ]] || [[ "${ESX_VER}" == "3.0.0" ]]; then
-    VMWARE_CMD=/usr/bin/vimsh
+	VMWARE_CMD=/usr/bin/vimsh
 else
-    echo "WARNING: Host type is not ESX 3.x+ or ESXi"
+	echo "WARNING: Host type is not ESX 3.x+ or ESXi"
 fi
 if [ "$VMWARE_CMD" != "" ]; then
-    for VM_CONF in `find /vmfs/volumes/ -name *.vmx`; do
-        echo "NOTICE: Trying to register $VM_CONF"
-        $VMWARE_CMD solo/registervm $VM_CONF
-    done
+	for VM_CONF in `find /vmfs/volumes/ -name *.vmx`; do
+		echo "NOTICE: Trying to register $VM_CONF"
+		$VMWARE_CMD solo/registervm $VM_CONF
+	done
 fi
 
 # loop
