updated to openQRM 4.9
git-svn-id: https://openqrm.svn.sourceforge.net/svnroot/openqrm/trunk@2171 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/src/etc/db/mysql/openqrm-mysql-functions b/src/etc/db/mysql/openqrm-mysql-functions
--- a/src/etc/db/mysql/openqrm-mysql-functions
+++ b/src/etc/db/mysql/openqrm-mysql-functions
@@ -15,7 +15,7 @@
 # You should have received a copy of the GNU General Public License
 # along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
 #
-# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
+# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
 #
 
 if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
@@ -72,15 +72,15 @@ function initialize_database() {
 	chmod +x /etc/cron.daily/$OPENQRM_DATABASE_MAINTENANCE_FNAME
     if [ -x "/etc/init.d/cron" ]; then
         if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d cron reload || exit $?
+            invoke-rc.d cron reload
         else
-            /etc/init.d/cron reload || exit $?
+            /etc/init.d/cron reload
         fi
 	elif [ -x "/etc/init.d/crond" ]; then
         if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d crond reload || exit $?
+            invoke-rc.d crond reload
         else
-            /etc/init.d/crond reload || exit $?
+            /etc/init.d/crond reload
         fi
     else
     	echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
@@ -130,15 +130,15 @@ function drop_database() {
 	rm -f /etc/cron.daily/$OPENQRM_DATABASE_MAINTENANCE_FNAME
     if [ -x "/etc/init.d/cron" ]; then
         if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d cron reload || exit $?
+            invoke-rc.d cron reload
         else
-            /etc/init.d/cron reload || exit $?
+            /etc/init.d/cron reload
         fi
 	elif [ -x "/etc/init.d/crond" ]; then
         if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-            invoke-rc.d crond reload || exit $?
+            invoke-rc.d crond reload
         else
-            /etc/init.d/crond reload || exit $?
+            /etc/init.d/crond reload
         fi
     else
     	echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
@@ -264,6 +264,16 @@ function db_update()  {
 
     #---------------------------------------------------------------------------
     # from 4.8 to 4.9 the following db changes are needed
+	# 1  > ALTER TABLE image_info ADD image_isactive INT(1);
+	# 2  > ALTER TABLE cloud_private_image ADD co_clone_on_deploy SMALLINT
+	# 3  > ALTER TABLE cloud_requests ADD cr_appliance_hostname VARCHAR(255)
+	# 4  > ALTER TABLE cloud_profiles ADD pr_appliance_hostname VARCHAR(255)
+	# 5 > insert into cloud_config(cc_id, cc_key, cc_value) values (34, 'appliance_hostname', 'true')";
+	# 6 > insert into cloud_config(cc_id, cc_key, cc_value) values (35, 'cloud_zones_client', 'false';
+	# 7 > insert into cloud_config(cc_id, cc_key, cc_value) values (36, 'cloud_zones_master_ip', '';
+	# 8 > create table cloud_transaction_failed(tf_id BIGINT, tf_ct_id BIGINT);
+	# 9 > insert into cloud_config(cc_id, cc_key, cc_value) values (37, 'cloud_external_ip', '')
+
     #---------------------------------------------------------------------------
     # from 4.9 to 5.0 the following db changes are needed
     #---------------------------------------------------------------------------
@@ -435,6 +445,73 @@ function db_update()  {
         fi
     fi
     echo "- Database sanity check for version 4.7 to 4.8 finished"
+
+
+    # 1  > ALTER TABLE image_info ADD image_isactive INT(1);
+	if ! check_column_in_table_exists image_info image_isactive; then
+		echo " -- db change : ALTER TABLE image_info ADD image_isactive INT(1)"
+		run_sql "ALTER TABLE image_info ADD image_isactive INT(1);"
+	fi
+
+    # if cloud enabled .....
+    if [ -e "$OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/cloud" ]; then
+
+		# 2  > ALTER TABLE image_info ADD image_isactive SMALLINT;
+		if ! check_column_in_table_exists cloud_private_image co_clone_on_deploy; then
+			echo " -- db change : ALTER TABLE cloud_private_image ADD co_clone_on_deploy SMALLINT"
+			run_sql "ALTER TABLE cloud_private_image ADD co_clone_on_deploy SMALLINT;"
+		fi
+		# 3  > ALTER TABLE cloud_requests ADD cr_appliance_hostname VARCHAR(255)
+		if ! check_column_in_table_exists cloud_requests cr_appliance_hostname; then
+			echo " -- db change : ALTER TABLE cloud_requests ADD cr_appliance_hostname VARCHAR(255)"
+			run_sql "ALTER TABLE cloud_requests ADD cr_appliance_hostname VARCHAR(255);"
+		fi
+		# 4  > ALTER TABLE cloud_profiles ADD pr_appliance_hostname VARCHAR(255)
+		if ! check_column_in_table_exists cloud_profiles pr_appliance_hostname; then
+			echo " -- db change : ALTER TABLE cloud_profiles ADD pr_appliance_hostname VARCHAR(255)"
+			run_sql "ALTER TABLE cloud_profiles ADD pr_appliance_hostname VARCHAR(255);"
+		fi
+        # 5 > insert into cloud_config(cc_id, cc_key, cc_value) values (34, 'appliance_hostname', 'true')";
+        if check_table_exists cloud_config; then
+            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 34; then
+                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (34, 'appliance_hostname', 'true')"
+                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (34, 'appliance_hostname', 'true');"
+            fi
+        fi
+		# 6 > insert into cloud_config(cc_id, cc_key, cc_value) values (35, 'cloud_zones_client', 'false');
+        if check_table_exists cloud_config; then
+            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 35; then
+                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (35, 'cloud_zones_client', 'false')"
+                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (35, 'cloud_zones_client', 'false');"
+            fi
+        fi
+		# 7 > insert into cloud_config(cc_id, cc_key, cc_value) values (36, 'cloud_zones_master_ip', '');
+        if check_table_exists cloud_config; then
+            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 36; then
+                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (36, 'cloud_zones_master_ip', '')"
+                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (36, 'cloud_zones_master_ip', '');"
+            fi
+        fi
+		# 8 > create table cloud_transaction_failed(tf_id BIGINT, tf_ct_id BIGINT);
+		if ! check_table_exists cloud_transaction_failed; then
+			echo " -- db change : create table cloud_transaction_failed(tf_id BIGINT, tf_ct_id BIGINT);"
+			run_sql "create table cloud_transaction_failed(tf_id BIGINT, tf_ct_id BIGINT);"
+		fi
+		# 9 > insert into cloud_config(cc_id, cc_key, cc_value) values (37, 'cloud_external_ip', '')
+        if check_table_exists cloud_config; then
+            if ! check_if_data_in_column_of_table_exists cloud_config cc_id 37; then
+                echo " -- db change : insert into cloud_config(cc_id, cc_key, cc_value) values (37, 'cloud_external_ip', '')"
+                run_sql "insert into cloud_config(cc_id, cc_key, cc_value) values (37, 'cloud_external_ip', '');"
+            fi
+        fi
+
+
+	fi
+
+    echo "- Database sanity check for version 4.8 to 4.9 finished"
+
+
+
 
 
 
diff --git a/src/etc/init.d/openqrm b/src/etc/init.d/openqrm
--- a/src/etc/init.d/openqrm
+++ b/src/etc/init.d/openqrm
@@ -30,7 +30,7 @@
 # You should have received a copy of the GNU General Public License
 # along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
 #
-# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
+# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
 #
 
 export LANG=C
@@ -94,9 +94,50 @@ function openqrm_server_init() {
 		done
 	fi
 
-	# here we start the init
-	# add automatic startup
-	openqrm_chkconfig add openqrm
+	# do some extra checks for redhat/centos regarding selinux + firewall
+	if [ -f /etc/redhat-release ]; then
+		# selinux disabled ?
+		if selinuxenabled; then
+			echo "ERROR: Found SELinux enabled!"
+			echo "ERROR: Please set SELINUX=disabled in /etc/selinux/config and reboot!"
+			exit 1
+		fi
+		# iptables ?
+		if which iptables 1>/dev/null; then
+			if iptables -L | grep REJECT 1>/dev/null; then
+				echo "NOTICE: Found iptables firewall enabled!"
+				echo "NOTICE: An active firewall may cause troubles during the initialization!"
+				echo "NOTICE: openQRM at least needs access to the following ports : 80, 443, $OPENQRM_EXEC_PORT"
+				echo
+				echo "NOTICE: Press 'c' to continue with the current iptables firewall configuration"
+				echo "NOTICE: Press 's' to stop the iptables firewall for the initialization"
+				while (:); do
+					read -n1 IPTABLES
+					if [ "$IPTABLES" == "c" ]; then
+						break
+					fi
+					if [ "$IPTABLES" == "s" ]; then
+						break
+					fi
+				done
+				if [ "$IPTABLES" == "c" ]; then
+					echo "... continuing with the current iptables firewall configuration"
+				elif [ "$IPTABLES" == "s" ]; then
+					echo "NOTICE: Stopping the iptables firewall"
+					if [ -x /etc/init.d/iptables ]; then
+						/etc/init.d/iptables stop
+					else
+						iptables --flush
+					fi
+				else
+					echo "ERROR: No such option!"
+					exit 1
+				fi
+
+
+			fi
+		fi
+	fi
 
 	# need to copy pxelinux.0 to the tftpboot dir
 	# sym-linking it does not work because the tftpd-server does not support symlinks
@@ -328,6 +369,10 @@ function openqrm_server_init() {
 			;;
 	esac
 
+	# here we start the init
+	# add automatic startup
+	openqrm_chkconfig add openqrm
+
 	# create unconfigured file containing a list of available network cards to setup openQRM on
 	ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i link | grep -v '^lo ' | awk {' print $1 '} > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured
 }
@@ -398,6 +443,12 @@ function openqrm_server_start() {
 	elif [ -f /etc/redhat-release ]; then
 		if ! ps ax | grep httpd | grep -v grep 1>/dev/null; then
 			$OPENQRM_WEBSERVER_INIT start
+			openqrm_chkconfig add httpd
+		fi
+		if ! ps ax | grep mysqld | grep -v grep 1>/dev/null; then
+			# make sure the db is up
+			/etc/init.d/mysqld start
+			openqrm_chkconfig add mysqld
 		fi
 	elif [ -f /etc/SuSE-release ]; then
 		if ! ps ax | grep apache | grep -v grep 1>/dev/null; then
diff --git a/src/etc/init.d/openqrm-client b/src/etc/init.d/openqrm-client
--- a/src/etc/init.d/openqrm-client
+++ b/src/etc/init.d/openqrm-client
@@ -30,7 +30,7 @@
 # You should have received a copy of the GNU General Public License
 # along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
 #
-# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
+# Copyright 2011, openQRM Enterprise GmbH <info@openqrm-enterprise.com>
 #
 
 export LANG=C
@@ -41,11 +41,19 @@ mkdir -p $(dirname $LOCKFILE)
 
 export `eval cat /proc/cmdline`	
 . /var/openqrm/openqrm-resource.conf
+# make sure to have a valid backup of the parameters, at least including the openQRM server ip
+if [ ! -f /var/openqrm/openqrm-resource.conf.last ]; then
+	/bin/cp -f /var/openqrm/openqrm-resource.conf /var/openqrm/openqrm-resource.conf.last
+fi
+if [ "$resource_mac" == "" ]; then
+	/bin/cp -f /var/openqrm/openqrm-resource.conf.last /var/openqrm/openqrm-resource.conf
+	. /var/openqrm/openqrm-resource.conf
+fi
 export OPENQRM_SERVER_BASE_DIR=$resource_basedir
 export OPENQRM_SOURCE_DIR=$resource_basedir/openqrm
-
 . $resource_basedir/openqrm/include/openqrm-functions
 . $resource_basedir/openqrm/include/openqrm-package-functions
+
 
 # define max-start-retries
 MAX_START_RETRY=120
@@ -92,6 +100,8 @@ function openqrm_client_start() {
 	echo "Starting openQRM-client"
 	openqrm_client_stop 1>/dev/null 2>&1
 	START_RETRY=0
+	LOOP_CONNECT=0
+	MAX_CONNECT=10
 	# checks
 	umount /initrd/lib/modules 1>/dev/null 2>&1
 	umount /initrd/boot 1>/dev/null 2>&1
@@ -103,15 +113,54 @@ function openqrm_client_start() {
 		mknod tty c 5 0
 		cd
 	fi
-	# if not in the initrd try to refresh the resource parameters
-	if [ ! -f /etc/initrd-devices.conf ]; then
-		/bin/cp -f /var/openqrm/openqrm-resource.conf /var/openqrm/openqrm-resource.conf.last
-		if ! $WGET -q -t 1 -T 4 -O /var/openqrm/openqrm-resource.conf "$openqrm_web_protocol://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$resource_mac"; then
-			# restore
-			/bin/cp -f /var/openqrm/openqrm-resource.conf.last /var/openqrm/openqrm-resource.conf
-			echo "NOTICE: Could not refresh resource-parameters. Using previous one."
-		else
-			. /var/openqrm/openqrm-resource.conf
+
+	# network up ?
+	echo "NOTICE: Checking connection to openQRM server at $resource_openqrmserver"
+	while ! $WGET -q -t 1 -T 4 -O /dev/null "$openqrm_web_protocol://$resource_openqrmserver/openqrm/action/resource-monitor.php"; do
+		echo -n "."
+		sleep 2
+		LOOP_CONNECT=$(( LOOP_CONNECT + 1 ))
+		if [ "$LOOP_CONNECT" == "$MAX_CONNECT" ]; then
+			echo "WARNING: Could not connect to openQRM server at $resource_openqrmserver! Trying to continue ..."
+			break
+		fi
+	done
+	# check if we have resource_mac, if not try to find the right interface integrated in openQRM
+	if ifconfig -a | grep ^eth | grep -i $resource_mac &>/dev/null; then
+		# if not in the initrd try to refresh the resource parameters
+		if [ ! -f /etc/initrd-devices.conf ]; then
+			if ! $WGET -q -t 1 -T 4 -O /var/openqrm/openqrm-resource.conf "$openqrm_web_protocol://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$resource_mac"; then
+				# restore
+				/bin/cp -f /var/openqrm/openqrm-resource.conf.last /var/openqrm/openqrm-resource.conf
+				echo "NOTICE: Could not refresh resource-parameters. Using previous one."
+			else
+				. /var/openqrm/openqrm-resource.conf
+			fi
+		fi
+	else
+		# here we do not found the resource_mac on one of the systems network cards
+		# assuming auto-install or clone to local-disk
+		/bin/cp -f /var/openqrm/openqrm-resource.conf /var/openqrm/openqrm-resource.conf.previous_res
+		for RESOURCE_MAC in `ifconfig -a | grep ^eth | grep -v ":oq" | awk '{ print $5 }'`; do
+			echo "NOTICE: Refreshing resource-parameters. Trying $RESOURCE_MAC."
+			if $WGET -q -t 1 -T 4 -O /var/openqrm/openqrm-resource.conf "$openqrm_web_protocol://$resource_openqrmserver/openqrm/action/resource-monitor.php?resource_command=get_parameter&resource_mac=$RESOURCE_MAC"; then
+				if grep -i $RESOURCE_MAC /var/openqrm/openqrm-resource.conf &>/dev/null; then
+					. /var/openqrm/openqrm-resource.conf
+					break
+				fi
+			fi
+		done
+	fi
+
+	# do some extra checks for redhat/centos regarding firewall
+	if [ -f /etc/redhat-release ]; then
+		# iptables ?
+		if which iptables 1>/dev/null; then
+			if iptables -L | grep REJECT 1>/dev/null; then
+				echo "NOTICE: Found iptables firewall enabled!"
+				echo "NOTICE: Inserting rule to allow access to the openQRM management port $resource_execdport"
+				iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport $resource_execdport -j ACCEPT
+			fi
 		fi
 	fi
 
@@ -185,8 +234,9 @@ function openqrm_client_start() {
 	esac
 
 	if [ ! -f /etc/initrd-devices.conf ]; then
-		# upate package manager, the boot-services may want to install additional os-deps
-		openqrm_update_package_manager
+		# upate package manager, the boot-services may want to install additional os-deps, disabled for now
+		# openqrm_update_package_manager
+
 		# start boot-services from enabled plugins
 		for boot_service in $openqrm_boot_services; do
 			openqrm_boot_service $boot_service start
@@ -242,6 +292,16 @@ function openqrm_client_stop() {
 	for OPENQRM_PID in `ps ax 2>/dev/null | grep openqrm-monitord | grep -v grep | awk {' print $1 '}`; do
 		kill $OPENQRM_PID
 	done
+
+	# remove firewall rule for exec port
+	if [ -f /etc/redhat-release ]; then
+		# iptables ?
+		if which iptables 1>/dev/null; then
+			if iptables -L | grep REJECT 1>/dev/null; then
+				iptables -D INPUT -m state --state NEW -m tcp -p tcp --dport $resource_execdport -j ACCEPT 2>/dev/null
+			fi
+		fi
+	fi
 	/bin/rm -f ${LOCKFILE}
 }
 
