fixed package-management system implemented package update
git-svn-id: https://openqrm.svn.sourceforge.net/svnroot/openqrm/trunk@2328 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/src/bin/openqrm-update b/src/bin/openqrm-update
--- a/src/bin/openqrm-update
+++ b/src/bin/openqrm-update
@@ -43,6 +43,7 @@ function update_usage() {
 	echo "`basename $0` pre <-f>"
 	echo "`basename $0` base <-f>"
 	echo "`basename $0` post <-f>"
+	echo "`basename $0` initrds <-f>"
 	echo
 }
 
@@ -253,7 +254,13 @@ function post_update() {
 function base_update() {
 	echo "- Running base update phase"
 	# re-source main config
-	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
+	if [ ! -f "$OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/etc/openqrm-server.conf" ]; then
+		echo "ERROR: Applying base-update before pre-update phase ! Trying to continue ..."
+		sleep 5
+		. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
+	else
+		. $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/etc/openqrm-server.conf
+	fi
 	# source db-functions according db-type
 	echo "- Database shema sanity check (databasetype $OPENQRM_DATABASE_TYPE)"
 	$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/$OPENQRM_DATABASE_TYPE/openqrm-$OPENQRM_DATABASE_TYPE-functions update
@@ -262,51 +269,102 @@ function base_update() {
 		echo "=> Please press <ENTER> to go on"
 		read
 	fi
+
+	# unpack all new boot-services
+	for OPENQRM_BOOTSERVICE in `find $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/ -name boot-service-*.tgz`; do
+		OPENQRM_BOOTSERVICE_FILENAME=`basename $OPENQRM_BOOTSERVICE`
+		OPENQRM_BOOTSERVICE_DIRNAME=`dirname $OPENQRM_BOOTSERVICE`
+		rm -rf $OPENQRM_BOOTSERVICE_DIRNAME/boot-service.tmp
+		mkdir $OPENQRM_BOOTSERVICE_DIRNAME/boot-service.tmp
+		if ! tar -C $OPENQRM_BOOTSERVICE_DIRNAME/boot-service.tmp -xzf $OPENQRM_BOOTSERVICE; then
+			echo "ERROR: Could not unpack boot-service $OPENQRM_BOOTSERVICE !"
+			sleep 5
+			rm -rf $OPENQRM_BOOTSERVICE_DIRNAME/boot-service.tmp
+		fi
+	done
+
+	# unpack all old boot-services
+	for OPENQRM_OLD_BOOTSERVICE in `find $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/plugins/ -name boot-service-*.tgz`; do
+		OPENQRM_OLD_BOOTSERVICE_FILENAME=`basename $OPENQRM_OLD_BOOTSERVICE`
+		OPENQRM_OLD_BOOTSERVICE_DIRNAME=`dirname $OPENQRM_OLD_BOOTSERVICE`
+		rm -rf $OPENQRM_OLD_BOOTSERVICE_DIRNAME/boot-service.tmp
+		mkdir $OPENQRM_OLD_BOOTSERVICE_DIRNAME/boot-service.tmp
+		if ! tar -C $OPENQRM_OLD_BOOTSERVICE_DIRNAME/boot-service.tmp -xzf $OPENQRM_OLD_BOOTSERVICE; then
+			echo "ERROR: Could not unpack boot-service $OPENQRM_OLD_BOOTSERVICE !"
+			sleep 5
+			rm -rf $OPENQRM_OLD_BOOTSERVICE_DIRNAME/boot-service.tmp
+		fi
+	done
+
 	# config file sanity check
 	for OPENQRM_CONF_FILE in `find $OPENQRM_SERVER_BASE_DIR/openqrm/ -name *.conf | cut -d'/' -f5-`; do
-		echo "  - Checking config file $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE"
-		if ! diff $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE 1>/dev/null 2>/dev/null; then
-			while (true); do
-				echo "  - Changes detected for config file $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE"
-				if [ "$FORCE_UPDATE" == "false" ]; then
-					echo "  - v - View changes"
-					echo "  - a - Try to apply old configuration"
-					echo "  - k - Apply new config file"
-					echo
+		if [ -f "$OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE" ]; then
+			echo "  - Checking config file $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE"
+			if ! diff $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE 1>/dev/null 2>/dev/null; then
+				while (true); do
+					echo "  - Changes detected for config file $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE"
+					if [ "$FORCE_UPDATE" == "false" ]; then
+						echo "  - v - View changes"
+						echo "  - a - Try to apply old configuration"
+						echo "  - k - Apply new config file"
+						echo
 
-					read -n1 APPLY_OLD_CONFIG
-					case "$APPLY_OLD_CONFIG" in
-						v)
-							echo "  - Displaying changes"
-							echo
-							if [ ! -f "$OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE" ]; then
-								echo "NOTICE: $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE does not exist"
-							elif [ !-f "$OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE" ]; then
-								echo "NOTICE: $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE does not exist"
-							else
-								diff $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE
-							fi
-							;;
-						a)
-							echo "  - Trying to apply old configuration"
-							openqrm_apply_old_config  $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE
-							echo
-							break
-							;;
-						k)
-							echo "   - Keeping new configuration"
-							break
-							;;
-					esac
-				else
-					echo
-					echo "  - Force enabled. Trying to apply old configuration"
-					openqrm_apply_old_config  $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE
-					echo
-					break
-				fi
-			done
+						read -n1 APPLY_OLD_CONFIG
+						case "$APPLY_OLD_CONFIG" in
+							v)
+								echo "  - Displaying changes"
+								echo
+								if [ ! -f "$OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE" ]; then
+									echo "NOTICE: $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE does not exist"
+								elif [ !-f "$OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE" ]; then
+									echo "NOTICE: $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE does not exist"
+								else
+									diff $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE
+								fi
+								;;
+							a)
+								echo "  - Trying to apply old configuration"
+								openqrm_apply_old_config  $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE
+								echo
+								break
+								;;
+							k)
+								echo "   - Keeping new configuration"
+								break
+								;;
+						esac
+					else
+						echo
+						echo "  - Force enabled. Trying to apply old configuration"
+						openqrm_apply_old_config  $OPENQRM_SERVER_BASE_DIR/openqrm/$OPENQRM_CONF_FILE $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/$OPENQRM_CONF_FILE
+						echo
+						break
+					fi
+				done
+			fi
 		fi
+	done
+
+	# pack all new boot-services
+	for OPENQRM_BOOTSERVICE in `find $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/ -name boot-service-*.tgz`; do
+		OPENQRM_BOOTSERVICE_FILENAME=`basename $OPENQRM_BOOTSERVICE`
+		OPENQRM_BOOTSERVICE_DIRNAME=`dirname $OPENQRM_BOOTSERVICE`
+		TIMESTAMP=`date +%s`
+		mv -f $OPENQRM_BOOTSERVICE $OPENQRM_BOOTSERVICE.$TIMESTAMP
+		cd $OPENQRM_BOOTSERVICE_DIRNAME/boot-service.tmp/
+		if ! tar -czf $OPENQRM_BOOTSERVICE *; then
+			echo "ERROR: Could not re-pack boot-service $OPENQRM_BOOTSERVICE !"
+			sleep 5
+		fi
+		cd -
+		rm -rf $OPENQRM_BOOTSERVICE_DIRNAME/boot-service.tmp
+	done
+
+	# clean up old boot-services
+	for OPENQRM_OLD_BOOTSERVICE in `find $OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/plugins/ -name boot-service-*.tgz`; do
+		OPENQRM_OLD_BOOTSERVICE_FILENAME=`basename $OPENQRM_OLD_BOOTSERVICE`
+		OPENQRM_OLD_BOOTSERVICE_DIRNAME=`dirname $OPENQRM_OLD_BOOTSERVICE`
+		rm -rf $OPENQRM_OLD_BOOTSERVICE_DIRNAME/boot-service.tmp
 	done
 
 	# custom updates from openQRM 4.6 to 4.7
@@ -326,6 +384,73 @@ function base_update() {
 	rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/boot-service-linuxcoe.tgz
 
 }
+
+
+
+
+function initrd_update() {
+	echo "- Updating initrds"
+	CURRENT_UPDATE_DIR=`pwd`
+
+
+	for INITRD_FILE in `ls $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/initrd-*.img`; do
+		UPDATE_OPENQRM_INITRD=false
+
+		if [ "$FORCE_UPDATE" == "false" ]; then
+			echo "    - y - Update $INITRD_FILE"
+			echo "    - n - Skip update of $INITRD_FILE"
+			echo
+			read -n1 APPLY_INITRD_UPDATE
+
+			case "$APPLY_INITRD_UPDATE" in
+				y)
+					echo "   - Updateing $INITRD_FILE"
+					UPDATE_OPENQRM_INITRD=true
+					;;
+				*)
+					echo "   - Keeping old initrd $INITRD_FILE"
+					UPDATE_OPENQRM_INITRD=false
+					;;
+			esac
+		else
+			echo "   - Force enabled. Updateing $INITRD_FILE"
+			UPDATE_OPENQRM_INITRD=true
+		fi
+
+		if [ "$UPDATE_OPENQRM_INITRD" == "true" ]; then
+			INITRD_FILENAME=`basename $INITRD_FILE`
+			rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/openqrm-initrd-update
+			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/openqrm-initrd-update
+			rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/openqrm-initrd-update/$INITRD_FILENAME
+			cp -f $INITRD_FILE $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/openqrm-initrd-update/$INITRD_FILENAME.gz
+			cd $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/openqrm-initrd-update/
+			# unpack
+			if ! gunzip < $INITRD_FILENAME.gz | cpio --extract --preserve; then
+				rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/openqrm-initrd-update
+				echo "ERROR: Could not gunzip $INITRD_FILE. Continuing ..."
+				continue
+			fi
+			rm -f $INITRD_FILENAME.gz
+			# update linuxrc
+			cp -af $OPENQRM_SERVER_BASE_DIR/openqrm//etc/templates/openqrm-linuxrc init
+			chmod +x init
+			# pack again
+			if ! find . | cpio -o -H newc | gzip -9 > $INITRD_FILE.new; then
+				rm -f $INITRD_FILE.new
+				rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/openqrm-initrd-update
+				echo "ERROR: Could not re-pack $INITRD_FILE. Continuing ..."
+				continue
+			fi
+			cp -f $INITRD_FILE.new $INITRD_FILE
+			rm -f $INITRD_FILE.new
+			# cleanup
+			cd $CURRENT_UPDATE_DIR
+			rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/openqrm-initrd-update
+		fi
+	done
+
+}
+
 
 
 
@@ -350,6 +475,9 @@ case "$1" in
 		;;
 	base)
 		base_update
+		;;
+	initrds)
+		initrd_update
 		;;
 	*)
 		update_usage
diff --git a/src/debian/openqrm.postinst b/src/debian/openqrm.postinst
--- a/src/debian/openqrm.postinst
+++ b/src/debian/openqrm.postinst
@@ -65,184 +65,198 @@ openqrm_validate_ip() {
 
 case "$1" in
     configure)
-        # copy pxelinux.0, tftdp does not support sym-linking it
-        mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot
-        if [ ! -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0 ]; then
-            if [ -f /usr/lib/syslinux/pxelinux.0 ]; then
-                cp -a /usr/lib/syslinux/pxelinux.0 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0
-            elif [ -f /usr/share/syslinux/pxelinux.0 ]; then
-                cp -a /usr/share/syslinux/pxelinux.0 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0
-            else
-                log_failure_msg "Cannot find pxelinux.0 on this system"
-                exit 1
-            fi
-        fi
-        # make sure apache is up + running
-        if ! ps ax | grep apache2 | grep -v grep 1>/dev/null; then
-            $OPENQRM_WEBSERVER_INIT start
-        fi
 
-        # link the web application directory to the documentroot
-        ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/web/ $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm
+		# is this an update ?
+		if [ -f "$OPENQRM_SERVER_BASE_DIR/openqrm_pre_update/etc/openqrm-server.conf" ]; then
+			if [ -x "$OPENQRM_SERVER_BASE_DIR/openqrm/bin/openqrm-update" ]; then
+				$OPENQRM_SERVER_BASE_DIR/openqrm/bin/openqrm-update base -f
+				$OPENQRM_SERVER_BASE_DIR/openqrm/bin/openqrm-update post -f
+				$OPENQRM_SERVER_BASE_DIR/openqrm/bin/openqrm-update initrds -f
+			fi
+		else
+			# it is a fresh install
 
-        # the default apache config normally does not allow to override the authconfig (needed for basic auth)
-        # so we allow it for the openqrm directory
-        cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" > /etc/apache2/conf.d/openqrm-httpd.conf
+			# copy pxelinux.0, tftdp does not support sym-linking it
+			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot
+			if [ ! -f $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0 ]; then
+				if [ -f /usr/lib/syslinux/pxelinux.0 ]; then
+					cp -a /usr/lib/syslinux/pxelinux.0 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0
+				elif [ -f /usr/share/syslinux/pxelinux.0 ]; then
+					cp -a /usr/share/syslinux/pxelinux.0 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.0
+				else
+					log_failure_msg "Cannot find pxelinux.0 on this system"
+					exit 1
+				fi
+			fi
+			# make sure apache is up + running
+			if ! ps ax | grep apache2 | grep -v grep 1>/dev/null; then
+				$OPENQRM_WEBSERVER_INIT start
+			fi
 
-        # ssl ?
-        if [ "$OPENQRM_WEB_PROTOCOL" = "https" ]; then
-            echo "Setting up SSL secured openQRM Website"
-            # apache ssl setup
-            if ! a2enmod ssl; then
-                echo "ERROR: Could not enable SSL in the Apache webserver ! Exiting."
-                exit 1
-            fi
-            # check for hostname settings
-            ETCHOSTS=/etc/hosts
-            MYHOSTNAME=`hostname`
-            if grep $MYHOSTNAME $ETCHOSTS | grep 127.0. 1>/dev/null || ! grep $MYHOSTNAME $ETCHOSTS 1>/dev/null; then
-                echo "Found system hostname $MYHOSTNAME connected to loopback interface"
-                echo "! This causes troubles while enabling SSL for the apache webserver !"
-                AVAIL_IPS=`ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i -A1 link | grep -v lo | grep inet | grep -v 127.0.0.1 | cut -d':' -f2 | awk {' print $1 '}`
-                while (true); do
-                    echo "Please select one of the following ip-addresses"
-                    echo "to be connected to the systems hostname $MYHOSTNAME :"
-                    echo "$AVAIL_IPS"
-                    echo -n " : "
-                    read HOSTIP
-                    if openqrm_validate_ip "$HOSTIP"; then
-                        if echo $AVAIL_IPS | grep "$HOSTIP" 1>/dev/null; then
-                            break;
-                        else
-                            echo "$HOSTIP is not available on this system!"
-                        fi
-                    else
-                        echo "$HOSTIP is invalid!"
-                    fi
-                    done
-                echo "Connecting $HOSTIP to $MYHOSTNAME in $ETCHOSTS"
-                # remove first
-                sed -i -e "s/.*$MYHOSTNAME.*//g" $ETCHOSTS
-                sed -i -e "s/.*openQRM.*//g" $ETCHOSTS
-                # make sure we did not remove the loopback entry copmletely
-                if ! grep "127.0.*.localhost" $ETCHOSTS 1>/dev/null; then
-                    echo "127.0.0.1	localhost" >> $ETCHOSTS.new
-                    cat $ETCHOSTS >> $ETCHOSTS.new
-                    mv -f $ETCHOSTS.new $ETCHOSTS
-                fi
-                echo "# added by openQRM" >> $ETCHOSTS
-                echo "$HOSTIP	$MYHOSTNAME" >> $ETCHOSTS
+			# link the web application directory to the documentroot
+			ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/web/ $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm
 
-            fi
+			# the default apache config normally does not allow to override the authconfig (needed for basic auth)
+			# so we allow it for the openqrm directory
+			cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-httpd.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" > /etc/apache2/conf.d/openqrm-httpd.conf
 
-            # creating the cert + key
-            PRIVATE_KEY=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/private/openqrm-private.key
-            CERTIFICATE_FILE=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/cert/openqrm.crt
-            VALID_DAYS=3650
-            mkdir -p `dirname $PRIVATE_KEY`
-            mkdir -p `dirname $CERTIFICATE_FILE`
-            echo "-> Creating new private/public-keys without passphrase for server"
-            rm -f $PRIVATE_KEY
-            openssl genrsa -out $PRIVATE_KEY 1024
-            echo "-> Creating selfsigned certificate"
-            rm -f $CERTIFICATE_FILE
-            openssl req -new -days $VALID_DAYS -key $PRIVATE_KEY -x509 -out $CERTIFICATE_FILE
-            # openQRM apache ssl config
-            cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-https.conf | \
-                sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | \
-                sed -e "s#@@OPENQRM_WEBSERVER_DOCUMENT_ROOT@@#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" \
-                > /etc/apache2/conf.d/openqrm-https.conf
-        fi
+			# ssl ?
+			if [ "$OPENQRM_WEB_PROTOCOL" = "https" ]; then
+				echo "Setting up SSL secured openQRM Website"
+				# apache ssl setup
+				if ! a2enmod ssl; then
+					echo "ERROR: Could not enable SSL in the Apache webserver ! Exiting."
+					exit 1
+				fi
+				# check for hostname settings
+				ETCHOSTS=/etc/hosts
+				MYHOSTNAME=`hostname`
+				if grep $MYHOSTNAME $ETCHOSTS | grep 127.0. 1>/dev/null || ! grep $MYHOSTNAME $ETCHOSTS 1>/dev/null; then
+					echo "Found system hostname $MYHOSTNAME connected to loopback interface"
+					echo "! This causes troubles while enabling SSL for the apache webserver !"
+					AVAIL_IPS=`ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i -A1 link | grep -v lo | grep inet | grep -v 127.0.0.1 | cut -d':' -f2 | awk {' print $1 '}`
+					while (true); do
+						echo "Please select one of the following ip-addresses"
+						echo "to be connected to the systems hostname $MYHOSTNAME :"
+						echo "$AVAIL_IPS"
+						echo -n " : "
+						read HOSTIP
+						if openqrm_validate_ip "$HOSTIP"; then
+							if echo $AVAIL_IPS | grep "$HOSTIP" 1>/dev/null; then
+								break;
+							else
+								echo "$HOSTIP is not available on this system!"
+							fi
+						else
+							echo "$HOSTIP is invalid!"
+						fi
+						done
+					echo "Connecting $HOSTIP to $MYHOSTNAME in $ETCHOSTS"
+					# remove first
+					sed -i -e "s/.*$MYHOSTNAME.*//g" $ETCHOSTS
+					sed -i -e "s/.*openQRM.*//g" $ETCHOSTS
+					# make sure we did not remove the loopback entry copmletely
+					if ! grep "127.0.*.localhost" $ETCHOSTS 1>/dev/null; then
+						echo "127.0.0.1	localhost" >> $ETCHOSTS.new
+						cat $ETCHOSTS >> $ETCHOSTS.new
+						mv -f $ETCHOSTS.new $ETCHOSTS
+					fi
+					echo "# added by openQRM" >> $ETCHOSTS
+					echo "$HOSTIP	$MYHOSTNAME" >> $ETCHOSTS
 
-        $OPENQRM_WEBSERVER_INIT reload
+				fi
 
-        # create the .htaccess file
-        cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-htaccess.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htaccess
+				# creating the cert + key
+				PRIVATE_KEY=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/private/openqrm-private.key
+				CERTIFICATE_FILE=$OPENQRM_SERVER_BASE_DIR/openqrm/etc/ssl/cert/openqrm.crt
+				VALID_DAYS=3650
+				mkdir -p `dirname $PRIVATE_KEY`
+				mkdir -p `dirname $CERTIFICATE_FILE`
+				echo "-> Creating new private/public-keys without passphrase for server"
+				rm -f $PRIVATE_KEY
+				openssl genrsa -out $PRIVATE_KEY 1024
+				echo "-> Creating selfsigned certificate"
+				rm -f $CERTIFICATE_FILE
+				openssl req -new -days $VALID_DAYS -key $PRIVATE_KEY -x509 -out $CERTIFICATE_FILE
+				# openQRM apache ssl config
+				cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-https.conf | \
+					sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" | \
+					sed -e "s#@@OPENQRM_WEBSERVER_DOCUMENT_ROOT@@#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" \
+					> /etc/apache2/conf.d/openqrm-https.conf
+			fi
 
-        # create the default admin user
-        htpasswd -bc $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd openqrm openqrm
-        chmod 666 $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd
+			$OPENQRM_WEBSERVER_INIT reload
 
-        # create the image-auth dir
-        mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/web/action/image-auth
-        chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/web/action/image-auth
+			# create the .htaccess file
+			cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/httpd/openqrm-htaccess.conf | sed -e "s#OPENQRM_WEBSERVER_DOCUMENT_ROOT#$OPENQRM_WEBSERVER_DOCUMENT_ROOT#g" > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htaccess
 
-        # link the tftpboot/boot dir to the boot-services
-        rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/boot
-        ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/ $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/boot
+			# create the default admin user
+			htpasswd -bc $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd openqrm openqrm
+			chmod 666 $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd
 
-        # create the openqrm-client link in the right arch
-        KERNEL_ARCH=`uname -m`
-        if echo $KERNEL_ARCH | grep i.*86 1>/dev/null; then
-            # i386
-            OPENQRM_CLIENT_ARCH=i386
-            OPENQRM_ADDITIONAL_ARCH=x86_64
-        else
-            OPENQRM_CLIENT_ARCH=$KERNEL_ARCH
-            OPENQRM_ADDITIONAL_ARCH=i386
-        fi
-        # find out the short distri name
-        if [ -f /etc/debian_version ]; then
-            # debian or ubuntu, try to find out without lsb-release which may not be installed
-            if grep -i ubuntu /etc/apt/sources.list 1>/dev/null; then
-                OPENQRM_SHORT_DISTRI_NAME="ubuntu"
-            else
-                OPENQRM_SHORT_DISTRI_NAME="debian"
-            fi
-        elif [ -f /etc/redhat-release ]; then
-            OPENQRM_SHORT_DISTRI_NAME="centos"
-        fi
-        THISDIR=`pwd`
-        cd $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/
-        ln -sf openqrm-client.tgz openqrm-client.$OPENQRM_CLIENT_ARCH.tgz
-        ln -sf openqrm-client.$OPENQRM_SHORT_DISTRI_NAME.$OPENQRM_ADDITIONAL_ARCH.tgz openqrm-client.$OPENQRM_ADDITIONAL_ARCH.tgz
-        cd $THISDIR
+			# create the image-auth dir
+			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/web/action/image-auth
+			chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/web/action/image-auth
+			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/tmp
+			chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/tmp
 
-        # init the remote execution layer
-        mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool/
-        chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool
-        rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear
-        mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/
-        $OPENQRM_SERVER_BASE_DIR/openqrm/bin/dropbearkey -t rsa -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
+			# link the tftpboot/boot dir to the boot-services
+			rm -f $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/boot
+			ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/ $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/boot
 
-        # allow the webserver user to read it
-        chmod 600 $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
+			# create the openqrm-client link in the right arch
+			KERNEL_ARCH=`uname -m`
+			if echo $KERNEL_ARCH | grep i.*86 1>/dev/null; then
+				# i386
+				OPENQRM_CLIENT_ARCH=i386
+				OPENQRM_ADDITIONAL_ARCH=x86_64
+			else
+				OPENQRM_CLIENT_ARCH=$KERNEL_ARCH
+				OPENQRM_ADDITIONAL_ARCH=i386
+			fi
+			# find out the short distri name
+			if [ -f /etc/debian_version ]; then
+				# debian or ubuntu, try to find out without lsb-release which may not be installed
+				if grep -i ubuntu /etc/apt/sources.list 1>/dev/null; then
+					OPENQRM_SHORT_DISTRI_NAME="ubuntu"
+				else
+					OPENQRM_SHORT_DISTRI_NAME="debian"
+				fi
+			elif [ -f /etc/redhat-release ]; then
+				OPENQRM_SHORT_DISTRI_NAME="centos"
+			fi
+			THISDIR=`pwd`
+			cd $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/
+			ln -sf openqrm-client.tgz openqrm-client.$OPENQRM_CLIENT_ARCH.tgz
+			ln -sf openqrm-client.$OPENQRM_SHORT_DISTRI_NAME.$OPENQRM_ADDITIONAL_ARCH.tgz openqrm-client.$OPENQRM_ADDITIONAL_ARCH.tgz
+			cd $THISDIR
 
-        # create authorized_keys
-        PUBLIC_KEY=`$OPENQRM_SERVER_BASE_DIR/openqrm/bin/dropbearkey -y -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key | grep ssh`
-        if [ ! -d /root/.ssh ]; then
-            mkdir -p /root/.ssh
-            chmod 700 /root/.ssh
-        fi
-        if [ ! -f /root/.ssh/authorized_keys ]; then
-            echo "$PUBLIC_KEY" > /root/.ssh/authorized_keys
-            chmod 600 /root/.ssh/authorized_keys
-        else
-            OPENQRM_HOST=`echo $PUBLIC_KEY | awk {' print $3 '}`
-            if grep $OPENQRM_HOST /root/.ssh/authorized_keys 1>/dev/null; then
-                sed -i -e "s#.*$OPENQRM_HOST.*##g" /root/.ssh/authorized_keys
-            fi
-            echo "$PUBLIC_KEY" >> /root/.ssh/authorized_keys
-            chmod 600 /root/.ssh/authorized_keys
-        fi
-        # and put it in the boot-service dir for the resources to download
-        echo "$PUBLIC_KEY" > $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/openqrm-server-public-rsa-key
-        ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/openqrm-server-public-rsa-key $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/openqrm-server-public-rsa-key
-		# create the command-queue dir
-		mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool/ $OPENQRM_SERVER_BASE_DIR/openqrm/var/lock/
-		chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool $OPENQRM_SERVER_BASE_DIR/openqrm/var/lock/
+			# init the remote execution layer
+			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool/
+			chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool
+			rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear
+			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/
+			dropbearkey -t rsa -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
 
-        # create unconfigured file containing a list of available network cards to setup openQRM on
-        ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i link | grep -v lo | awk {' print $1 '} > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured
+			# allow the webserver user to read it
+			chmod 600 $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key
+
+			# create authorized_keys
+			PUBLIC_KEY=`dropbearkey -y -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key | grep ssh`
+			if [ ! -d /root/.ssh ]; then
+				mkdir -p /root/.ssh
+				chmod 700 /root/.ssh
+			fi
+			if [ ! -f /root/.ssh/authorized_keys ]; then
+				echo "$PUBLIC_KEY" > /root/.ssh/authorized_keys
+				chmod 600 /root/.ssh/authorized_keys
+			else
+				OPENQRM_HOST=`echo $PUBLIC_KEY | awk {' print $3 '}`
+				if grep $OPENQRM_HOST /root/.ssh/authorized_keys 1>/dev/null; then
+					sed -i -e "s#.*$OPENQRM_HOST.*##g" /root/.ssh/authorized_keys
+				fi
+				echo "$PUBLIC_KEY" >> /root/.ssh/authorized_keys
+				chmod 600 /root/.ssh/authorized_keys
+			fi
+			# and put it in the boot-service dir for the resources to download
+			echo "$PUBLIC_KEY" > $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/openqrm-server-public-rsa-key
+			ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/openqrm-server-public-rsa-key $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/openqrm-server-public-rsa-key
+			# create the command-queue dir
+			mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool/ $OPENQRM_SERVER_BASE_DIR/openqrm/var/lock/
+			chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/var/spool $OPENQRM_SERVER_BASE_DIR/openqrm/var/lock/
+
+			# create unconfigured file containing a list of available network cards to setup openQRM on
+			ifconfig -a | grep -v inet6  | grep -B1 inet | grep -i link | grep -v lo | awk {' print $1 '} > $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/unconfigured
+		fi
 
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    abort-upgrade|abort-remove|abort-deconfigure|upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
-        exit 1
+        echo "postinst called with argument \`$1'" >&2
+        exit 0
     ;;
 esac
 
