- added fencing function, improve HA handling - added constraint-checks for object removal - added cloud-hook, making the Virtualization types completely plug-able - added ha-hook to auto-create and fence VMs
git-svn-id: https://openqrm.svn.sourceforge.net/svnroot/openqrm/trunk@2062 f7cd0d49-994a-0410-81fc-ecfcdc9cdbae

diff --git a/src/plugins/xen/bin/openqrm-xen b/src/plugins/xen/bin/openqrm-xen
--- a/src/plugins/xen/bin/openqrm-xen
+++ b/src/plugins/xen/bin/openqrm-xen
@@ -78,9 +78,9 @@ fi
 
 function xen_usage() {
 	echo "Usage : $0 start/stop/reboot/remove/list <-n vm-name>"
-	echo "Usage : $0 create <-n vm-name> <-m mac-address> <-r memory> [-d disk-size] [-s swap-size] [ -c cpu-number]"
-	echo "Usage : $0 migrate <-n vm-name> <-i ip-address> <-t live/regular>"
-	echo "Usage : $0 setboot <-m mac-address> <-b local/net>"
+	echo "        $0 create <-n vm-name> <-m mac-address> <-r memory> [-d disk-size] [-s swap-size] [ -c cpu-number]"
+	echo "        $0 migrate <-n vm-name> <-i ip-address> <-t live/regular>"
+	echo "        $0 setboot <-m mac-address> <-b local/net>"
 	echo "        $0 post_vm_list <-u username> <-p password>"
 	echo "        $0 post_vm_config <-n vm-name> <-u username> <-p password>"
 	echo "        $0 update_vm_ram <-r memory> <-n vm-name>"
@@ -89,6 +89,7 @@ function xen_usage() {
 	echo "        $0 remove_vm_nic <-x nic-number> <-n vm-name>"
 	echo "        $0 add_vm_disk <-x disk-number> <-d disk-size> <-n vm-name>"
 	echo "        $0 remove_vm_disk <-x disk-number> <-n vm-name>"
+	echo "        $0 fence <-m mac-address>"
 	exit 1
 }
 
@@ -310,7 +311,7 @@ if [ "$XEN_COMMAND" == "post_vm_list" ]; then
 		fi
 else
 
-	if [ "$XEN_COMMAND" != "list" ] && [ "$XEN_COMMAND" != "setboot" ]; then
+	if [ "$XEN_COMMAND" != "list" ] && [ "$XEN_COMMAND" != "setboot" ]  && [ "$XEN_COMMAND" != "fence" ]; then
 		if [ "$XEN_VM_NAME" == "" ]; then
 			xen_usage
 		fi
@@ -824,6 +825,40 @@ case "$XEN_COMMAND" in
 		xen_lock release
         exit 0
 		;;
+
+	fence)
+        unset XEN_VM_NAME
+		if [ "$XEN_VM_MAC" == "" ]; then
+            echo "openQRM Xen-plugin: ERROR during fence. No mac-address given" | logger
+			xen_usage
+		fi
+		xen_lock aquire
+		echo "Fencing vm with mac $XEN_VM_MAC to boot from $XEN_VM_BOOT"
+        # this command is is running from the openQRM engine which does
+        # not know about the xen-name
+        for XEN_VM_NET_CONF in `find $OPENQRM_VM_DIR/ -name mac1`; do
+            XEN_VM_MAC_1=`cat $XEN_VM_NET_CONF 2>/dev/null`
+            if [ "$XEN_VM_MAC_1" == "$XEN_VM_MAC" ]; then
+                XEN_VM_NAME=`dirname $XEN_VM_NET_CONF`
+                XEN_VM_NAME=`basename $XEN_VM_NAME`
+                break
+            fi
+        done
+        if [ "$XEN_VM_NAME" == "" ]; then
+    		echo "Cloud not find Xen vm with mac $XEN_VM_MAC on this host"
+            echo "openQRM Xen-plugin: ERROR: Cloud not find Xen vm with mac $XEN_VM_MAC on this host" | logger
+            exit 1
+        fi
+		# stop hard
+        if xm destroy $XEN_VM_NAME; then
+            openqrm_post_event 0 "fence" 5 "openqrm-xen" "Forced stop for fencing Xen vm $XEN_VM_NAME"
+        else
+            openqrm_post_event 0 "fence" 3 "openqrm-xen" "Cloud not force stop Xen vm $XEN_VM_NAME. Trying to continue .."
+        fi
+		xen_lock release
+        exit 0
+		;;
+
 	*)
 		xen_usage
 		;;
